import { jsPDF } from "jspdf";

export const exportReport = () => {
  const report = JSON.parse(localStorage.getItem("report"));

  const doc = new jsPDF();

  // ================= HEADER =================

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("Portfolio Critic AI", 20, 18);

  doc.setFontSize(11);
  doc.text("AI Powered Portfolio Analysis Report", 20, 27);

  // Reset text color
  doc.setTextColor(0, 0, 0);

  let y = 50;

  const pageHeight = doc.internal.pageSize.getHeight();

  function checkPageBreak(spaceNeeded = 15) {
    if (y + spaceNeeded > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
  }

  // ================= DATE =================

  const analyzedOn = new Date().toLocaleString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });

  checkPageBreak(20);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${analyzedOn}`, 20, y);

  y += 15;

  // ================= SUMMARY =================

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Analysis Summary", 20, y);

  y += 12;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text("Overall Score", 20, y);

  doc.setFont("helvetica", "bold");
  doc.text(`${report.overallScore}/100`, 160, y);

  y += 18;

  doc.setDrawColor(220);
  doc.line(20, y, 190, y);

  y += 15;

  // ================= WEBSITE SCORES =================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Website Scores", 20, y);

  y += 12;

  const scores = [
    ["UI / UX", report.uiux],
    ["Accessibility", report.accessibility],
    ["SEO", report.seo],
    ["Performance", report.performance],
    ["Mobile Experience", report.mobileExperience],
  ];

  scores.forEach(([title, value]) => {
    doc.setFont("helvetica", "normal");
    doc.text(title, 25, y);

    doc.setFont("helvetica", "bold");
    doc.text(`${value}/100`, 160, y);

    y += 10;
  });

  y += 5;

  doc.setDrawColor(220);
  doc.line(20, y, 190, y);

  y += 15;

  // ================= STRENGTHS =================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Strengths", 20, y);

  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  report.strengths.forEach((item) => {
    checkPageBreak(20);

    doc.text(`• ${item}`, 25, y);
    y += 8;
  });

  y += 5;

  doc.setDrawColor(220);
  doc.line(20, y, 190, y);

  y += 15;

  checkPageBreak(20);

  // ================= WEAKNESSES =================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Weaknesses", 20, y);

  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  report.weaknesses.forEach((item) => {
    checkPageBreak(20);
    doc.text(`• ${item}`, 25, y);
    y += 8;
  });

  y += 5;

  doc.setDrawColor(220);
  doc.line(20, y, 190, y);

  y += 15;

  // ================= RECOMMENDATIONS =================

  checkPageBreak(20);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Recommendations", 20, y);

  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  report.recommendations.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 8;
  });

  // ================= FOOTER =================

  doc.setDrawColor(220);
  doc.line(20, 280, 190, 280);

  doc.setTextColor(120);

  doc.setFontSize(10);

  doc.text("Generated by Portfolio Critic AI", 20, 288);

  doc.text("© 2026 Portfolio Critic AI", 145, 288);

  // ================= SAVE =================

  doc.save("Portfolio_Report.pdf");
};
